<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <RootNamespace>DiscordRaidFeed.Client</RootNamespace>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <Version>1.0.0</Version>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AssemblyName>DiscordRaidFeed.Client</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony"><HintPath>$(SPTPath)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>$(SPTPath)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Comfort"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="DissonanceVoip"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\DissonanceVoip.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="spt-reflection"><HintPath>$(SPTPath)\BepInEx\plugins\spt\spt-reflection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Sirenix.Utilities"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Sirenix.Utilities.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Sirenix.Serialization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Sirenix.Utilities"><HintPath>$(SPTPath)\EscapeFromTarkov_Data\Managed\Sirenix.Utilities.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <Target Name="Deploy" AfterTargets="Build" Condition="'$(SPTPath)' != '' And '$(SkipDeploy)' != 'true'">
    <MakeDir Directories="$(SPTPath)\BepInEx\plugins\DiscordRaidFeed" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SPTPath)\BepInEx\plugins\DiscordRaidFeed" SkipUnchangedFiles="true" />
  </Target>
</Project>
